# Generated by Django 4.2.16 on 2025-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_brand_brand_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mnt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="mnt_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
