# Generated by Django 4.2.16 on 2025-02-11 00:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0045_brand_brand_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLensArrivalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_lens_id', models.IntegerField()),
                ('arrival_status', models.CharField(default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_arrival_statuses', to='api.order')),
            ],
        ),
    ]
